---
abstract: 'type constraints for dealing with relational databases'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  DBD::SQLite: 0
  Test::Modern: 0.002
  Test::TypeTiny: 0.008
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Types-DBI
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Types::DBI:
    file: lib/Types/DBI.pm
    version: 0.001
requires:
  DBI: 0
  Type::Tiny: 0.008
  perl: 5.008001
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Types-DBI/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Types-DBI
  homepage: https://metacpan.org/release/Types-DBI
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-types-dbi.git
version: 0.001
